# Generated by Django 6.0.4 on 2026-04-28 13:21

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('social_entities', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AbsoluteStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('likes_count', models.IntegerField()),
                ('views_count', models.IntegerField()),
                ('participants_count', models.IntegerField()),
                ('repost_count', models.IntegerField()),
                ('comms_count', models.IntegerField()),
                ('last_updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='abs_stats', to='social_entities.group')),
            ],
        ),
        migrations.CreateModel(
            name='Snapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('type', models.CharField(choices=[('DY', 'Daily'), ('HY', 'Hourly')], max_length=2)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='snapshot_stats', to='social_entities.group')),
            ],
        ),
        migrations.CreateModel(
            name='SnapshotStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('likes_count', models.IntegerField()),
                ('views_count', models.IntegerField()),
                ('participants_count', models.IntegerField()),
                ('repost_count', models.IntegerField()),
                ('comms_count', models.IntegerField()),
                ('coverage', models.IntegerField()),
                ('last_updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('snapshot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stats', to='stats.snapshot')),
            ],
        ),
    ]
