# Generated by Django 6.0.4 on 2026-05-04 19:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('stats', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='absolutestats',
            name='posts_count',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
