# Generated by Django 6.0.4 on 2026-05-06 19:12

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('social_entities', '0003_group_slug'),
        ('stats', '0002_absolutestats_posts_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='absolutestats',
            name='comms_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='absolutestats',
            name='likes_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='absolutestats',
            name='participants_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='absolutestats',
            name='posts_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='absolutestats',
            name='repost_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='absolutestats',
            name='views_count',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='BestPosts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('most_liked', models.IntegerField()),
                ('most_reposted', models.IntegerField()),
                ('most_commented', models.IntegerField()),
                ('most_viewed', models.IntegerField()),
                ('last_updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='best_posts',
                                            to='social_entities.group')),
            ],
        ),
    ]
