# Generated by Django 6.0.4 on 2026-05-06 19:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('stats', '0003_alter_absolutestats_comms_count_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='snapshot',
            name='type',
            field=models.CharField(choices=[('Daily', 'Daily'), ('Hourly', 'Hourly')], max_length=6),
        ),
    ]
