# Generated by Django 6.0.4 on 2026-05-06 19:52

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('stats', '0004_alter_snapshot_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='snapshotstats',
            old_name='participants_count',
            new_name='participants_delta',
        ),
    ]
