# Generated by Django 6.0.4 on 2026-05-06 19:53

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('stats', '0005_rename_participants_count_snapshotstats_participants_delta'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='snapshotstats',
            name='last_updated_at',
        ),
    ]
