# Generated by Django 6.0.4 on 2026-05-10 11:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('social_entities', '0004_alter_group_added_at'),
        ('stats', '0006_remove_snapshotstats_last_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='snapshot',
            name='type',
            field=models.CharField(choices=[('DAILY', 'DAILY'), ('HOURLY', 'HOURLY')], max_length=6),
        ),
        migrations.CreateModel(
            name='BestPostInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('likes_count', models.IntegerField()),
                ('comms_count', models.IntegerField()),
                ('views_count', models.IntegerField()),
                ('reposts_count', models.IntegerField()),
                ('content', models.CharField(max_length=150)),
                ('post_type', models.CharField(max_length=16)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='best_posts',
                                            to='social_entities.group')),
            ],
        ),
        migrations.DeleteModel(
            name='BestPosts',
        ),
    ]
