# Generated by Django 6.0.4 on 2026-05-10 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0007_alter_snapshot_type_bestpostinfo_delete_bestposts'),
    ]

    operations = [
        migrations.AddField(
            model_name='bestpostinfo',
            name='post_id',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
