# Generated by Django 6.0.4 on 2026-05-10 13:39

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('stats', '0008_bestpostinfo_post_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='bestpostinfo',
            name='last_updated_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
