# Generated by Django 6.0.4 on 2026-05-10 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0009_bestpostinfo_last_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bestpostinfo',
            name='post_id',
            field=models.BigIntegerField(),
        ),
    ]
