# Generated by Django 6.0.1 on 2026-01-29 17:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telegramtoken',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2026, 1, 29, 17, 41, 48, 55747, tzinfo=datetime.timezone.utc)),
        ),
    ]
