# Generated by Django 6.0.1 on 2026-01-29 17:52

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_telegramtoken_expires_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telegramtoken',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2026, 1, 29, 18, 7, 31, 503823, tzinfo=datetime.timezone.utc)),
        ),
        migrations.CreateModel(
            name='EmailActivate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=64, unique=True)),
                ('expires_at', models.DateTimeField(default=datetime.datetime(2026, 1, 30, 17, 52, 31, 504823, tzinfo=datetime.timezone.utc))),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
