# Generated by Django 6.0.1 on 2026-04-14 09:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('accounts', '0002_group_service_account_group_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='serviceaccount',
            name='groups',
        ),
        migrations.AddField(
            model_name='platform',
            name='alias',
            field=models.CharField(default='', max_length=16),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='group',
            name='service_account',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='groups',
                                    to='accounts.serviceaccount'),
        ),
    ]
