# Generated by Django 6.0.1 on 2026-04-14 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_serviceaccount_groups_platform_alias_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='platform',
            name='alias',
            field=models.CharField(db_index=True, max_length=16),
        ),
    ]
