# Generated by Django 6.0.1 on 2026-01-29 18:35

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_telegramtoken_expires_at_emailactivate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailactivate',
            name='expires_at',
            field=models.DateTimeField(default=accounts.models.default_expires_at),
        ),
        migrations.AlterField(
            model_name='telegramtoken',
            name='expires_at',
            field=models.DateTimeField(default=accounts.models.default_expires_at),
        ),
    ]
