# Generated by Django 6.0.1 on 2026-01-27 17:44

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_remove_customuser_phone_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='TelegramToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_token', models.CharField(max_length=64)),
                ('jwt_token', models.CharField(max_length=512)),
                ('expires_at', models.DateTimeField(default=datetime.datetime(2026, 1, 27, 17, 59, 8, 66822, tzinfo=datetime.timezone.utc))),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
