# Generated by Django 6.0.1 on 2026-04-21 09:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_platform_alias'),
        ('admin_panel', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='platform',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_panel.platform'),
        ),
        migrations.RemoveField(
            model_name='serviceaccount',
            name='platform',
        ),
        migrations.AlterField(
            model_name='group',
            name='service_account',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='groups', to='admin_panel.serviceaccount'),
        ),
        migrations.RemoveField(
            model_name='serviceaccountdata',
            name='account',
        ),
        migrations.DeleteModel(
            name='Platform',
        ),
        migrations.DeleteModel(
            name='ServiceAccount',
        ),
        migrations.DeleteModel(
            name='ServiceAccountData',
        ),
    ]
