# Generated by Django 6.0.1 on 2026-01-30 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_emailactivate_expires_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='vk_id',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='tg_id',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
    ]
