# Generated by Django 6.0.1 on 2026-01-27 17:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_telegramtoken'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telegramtoken',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2026, 1, 27, 18, 11, 51, 7500, tzinfo=datetime.timezone.utc)),
        ),
    ]
