# Generated by Django 6.0.1 on 2026-02-10 10:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_customuser_vk_id_alter_customuser_tg_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='tg_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='vk_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='VKTokens',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('refresh_vk_token', models.CharField(max_length=512)),
                ('access_vk_token', models.CharField(max_length=512)),
                ('id_vk_token', models.CharField(max_length=512)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
