# Generated by Django 6.0.1 on 2026-02-10 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_customuser_tg_id_alter_customuser_vk_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vktokens',
            name='expires_in',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
