# Generated by Django 6.0.1 on 2026-01-28 12:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_telegramtoken_expires_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telegramtoken',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2026, 1, 28, 12, 23, 7, 770380, tzinfo=datetime.timezone.utc)),
        ),
    ]
