# Generated by Django 6.0.1 on 2026-02-10 16:44

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_vktokens_expires_in'),
    ]

    operations = [
        migrations.AddField(
            model_name='vktokens',
            name='added_at',
            field=models.DateTimeField(default=accounts.models.default_expires_at),
        ),
    ]
