# Generated by Django 6.0.1 on 2026-03-02 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_vktokens_added_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='telegramtoken',
            old_name='jwt_token',
            new_name='access_token',
        ),
        migrations.AddField(
            model_name='telegramtoken',
            name='refresh_token',
            field=models.CharField(default='', max_length=512),
            preserve_default=False,
        ),
    ]
