# Generated by Django 6.0.1 on 2026-01-29 14:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_telegramtoken_expires_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telegramtoken',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2026, 1, 29, 14, 52, 22, 690364, tzinfo=datetime.timezone.utc)),
        ),
    ]
