# Generated by Django 6.0.1 on 2026-04-24 20:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='onetimetoken',
            name='created_at',
        ),
    ]
