# Generated by Django 6.0.4 on 2026-04-28 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_entities', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='slug',
            field=models.SlugField(default='', max_length=255, unique=True, verbose_name='URL'),
            preserve_default=False,
        ),
    ]
