# Generated by Django 6.0.4 on 2026-05-10 11:10

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_entities', '0003_group_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='added_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
