# Generated by Django 6.0.1 on 2026-04-22 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceaccount',
            name='is_activated',
            field=models.BooleanField(default=False),
        ),
    ]
