# Generated by Django 6.0.1 on 2026-04-24 14:36

import social_auth.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmailActivate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=64, unique=True)),
                ('expires_at', models.DateTimeField(default=social_auth.models.default_expires_at)),
            ],
        ),
        migrations.CreateModel(
            name='TelegramToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_token', models.CharField(max_length=64, unique=True)),
                ('access_token', models.CharField(max_length=512)),
                ('refresh_token', models.CharField(max_length=512)),
                ('expires_at', models.DateTimeField(default=social_auth.models.default_expires_at)),
            ],
        ),
        migrations.CreateModel(
            name='VKTokens',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('refresh_vk_token', models.CharField(max_length=512)),
                ('access_vk_token', models.CharField(max_length=512)),
                ('id_vk_token', models.TextField()),
                ('expires_in', models.IntegerField()),
                ('added_at', models.DateTimeField(default=social_auth.models.default_expires_at)),
            ],
        ),
    ]
