# Generated by Django 6.0.1 on 2026-04-24 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('is_activated', models.BooleanField(default=False)),
                ('app_id', models.CharField(blank=True, db_index=True, null=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='ServiceAccountData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_key', models.CharField(blank=True, max_length=256, null=True)),
                ('protected_key', models.CharField(blank=True, max_length=256, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=11, null=True, unique=True)),
                ('session_path', models.CharField(blank=True, max_length=256, null=True)),
            ],
        ),
    ]
