# Generated by Django 6.0.1 on 2026-04-26 12:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('service_accounts', '0001_initial'),
        ('social_entities', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceaccount',
            name='platform',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='social_entities.platform'),
        ),
        migrations.AddField(
            model_name='onetimetoken',
            name='account',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='one_time_token', to='service_accounts.serviceaccount'),
        ),
        migrations.AddField(
            model_name='serviceaccountdata',
            name='account',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='data', to='service_accounts.serviceaccount'),
        ),
    ]
